import { html } from "lit";
import { MDElement } from "../../material/element/element.js";

class AppImageComponent extends MDElement {
    render() {
        return html`
            <div
                style=""
                class="md-layout-grid"
            >
                <div
                    style=""
                    class="md-layout-grid__item md-layout-grid__item--expanded12 md-layout-grid__item--medium8 md-layout-grid__item--compact4"
                >
                    <md-image
                        src="https://placehold.co/112"
                        @onImageNativeLoad="${console.log}"
                        @onImageNativeError="${console.log}"
                    ></md-image>
                </div>
                <div
                    style=""
                    class="md-layout-grid__item md-layout-grid__item--expanded12 md-layout-grid__item--medium8 md-layout-grid__item--compact4"
                >
                    <md-image
                        style="width:112px;"
                        aspectRatio="16/9"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        aspectRatio="3/2"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        aspectRatio="4/3"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        aspectRatio="1/1"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        aspectRatio="3/4"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        aspectRatio="2/3"
                        src="https://placehold.co/112"
                    ></md-image>
                </div>
                <div
                    style=""
                    class="md-layout-grid__item md-layout-grid__item--expanded12 md-layout-grid__item--medium8 md-layout-grid__item--compact4"
                >
                    <md-image
                        style="width:112px;"
                        variant="rounded"
                        aspectRatio="16/9"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        variant="rounded"
                        aspectRatio="3/2"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        variant="rounded"
                        aspectRatio="4/3"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        variant="rounded"
                        aspectRatio="1/1"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        variant="rounded"
                        aspectRatio="3/4"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="width:112px;"
                        variant="rounded"
                        aspectRatio="2/3"
                        src="https://placehold.co/112"
                    ></md-image>
                </div>
                <div
                    style=""
                    class="md-layout-grid__item md-layout-grid__item--expanded12 md-layout-grid__item--medium8 md-layout-grid__item--compact4"
                >
                    <md-image
                        style="height:112px;"
                        aspectRatio="16/9"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        aspectRatio="3/2"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        aspectRatio="4/3"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        aspectRatio="1/1"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        aspectRatio="3/4"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        aspectRatio="2/3"
                        src="https://placehold.co/112"
                    ></md-image>
                </div>
                <div
                    style=""
                    class="md-layout-grid__item md-layout-grid__item--expanded12 md-layout-grid__item--medium8 md-layout-grid__item--compact4"
                >
                    <md-image
                        style="height:112px;"
                        variant="rounded"
                        aspectRatio="16/9"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        variant="rounded"
                        aspectRatio="3/2"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        variant="rounded"
                        aspectRatio="4/3"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        variant="rounded"
                        aspectRatio="1/1"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        variant="rounded"
                        aspectRatio="3/4"
                        src="https://placehold.co/112"
                    ></md-image>
                    <md-image
                        style="height:112px;"
                        variant="rounded"
                        aspectRatio="2/3"
                        src="https://placehold.co/112"
                    ></md-image>
                </div>
            </div>
        `;
    }
}

customElements.define("app-image", AppImageComponent);

export default document.createElement("app-image");
