import { Router } from "../lib/router/router";

// prettier-ignore
Router.init([
    // {path:'',load:() => import('./main/main.js').then(m=>m.default),children:[
    //     // {path:'blogs',load:() => import('./blogs/blogs.js').then(m=>m.default),children:[
    //     //     {path:':_id',load:() => import('./blog/blog.js').then(m=>m.default),children:[]},
    //     // ]},
    //     {path:'gesture',load:() => import('./gesture/gesture.js').then(m=>m.default),children:[]},
    //     {path:'ripple',load:() => import('./ripple/ripple.js').then(m=>m.default),children:[]},
    //     {path:'icon',load:() => import('./icon/icon.js').then(m=>m.default),children:[]},
    //     {path:'emoji',load:() => import('./emoji/emoji.js').then(m=>m.default),children:[]},
    //     {path:'button',load:() => import('./button/button.js').then(m=>m.default),children:[]},
    //     {path:'list',load:() => import('./list/list.js').then(m=>m.default),children:[]},
    //     {path:'data-table',load:() => import('./data-table/data-table.js').then(m=>m.default),children:[]},
    //     {path:'form-field',load:() => import('./form-field/form-field.js').then(m=>m.default),children:[]},
    //     {path:'text-field',load:() => import('./text-field/text-field.js').then(m=>m.default),children:[]},
    //     {path:'range-field',load:() => import('./range-field/range-field.js').then(m=>m.default),children:[]},
    // ]},
    // // {path:'admin',load:() => import('./admin/admin.js').then(m=>m.default),children:[
    // //     {path:'users',load:() => import('./users/users.js').then(m=>m.default),children:[
    // //         {path:':_id',load:() => import('./user/user.js').then(m=>m.default),children:[]},
    // //     ]},
    // // ]},
    // // {path:'auth',load:() => import('./auth/auth.js').then(m=>m.default),children:[
    // //     {path:'login',load:() => import('./login/login.js').then(m=>m.default),children:[]},
    // //     {path:'verify',load:() => import('./verify/verify.js').then(m=>m.default),children:[]},
    // //     {path:'register',load:() => import('./register/register.js').then(m=>m.default),children:[]},
    // // ]},
    // {path:'*',load:() => import('./error/error.js').then(m=>m.default),children:[]},

    {path:'',load:() => import('./main/main.js').then(m=>m.default),children:[

        {path:'ripple',load:() => import('./ripple/ripple.js').then(m=>m.default)},
        {path:'gesture',load:() => import('./gesture/gesture.js').then(m=>m.default)},
        {path:'popper',load:() => import('./popper/popper.js').then(m=>m.default)},
        {path:'button',load:() => import('./button/button.js').then(m=>m.default)},
        {path:'extended-fab',load:() => import('./extended-fab/extended-fab.js').then(m=>m.default)},
        {path:'fab',load:() => import('./fab/fab.js').then(m=>m.default)},
        {path:'icon-button',load:() => import('./icon-button/icon-button.js').then(m=>m.default)},
        {path:'badge',load:() => import('./badge/badge.js').then(m=>m.default)},
        {path:'progress-indicator',load:() => import('./progress-indicator/progress-indicator.js').then(m=>m.default)},
        {path:'snackbar',load:() => import('./snackbar/snackbar.js').then(m=>m.default)},
        {path:'tooltip',load:() => import('./tooltip/tooltip.js').then(m=>m.default)},
        {path:'dialog',load:() => import('./dialog/dialog.js').then(m=>m.default)},
        {path:'bottom-sheet',load:() => import('./bottom-sheet/bottom-sheet.js').then(m=>m.default)},
        {path:'bottom-app-bar',load:() => import('./bottom-app-bar/bottom-app-bar.js').then(m=>m.default)},
        {path:'navigation-bar',load:() => import('./navigation-bar/navigation-bar.js').then(m=>m.default)},
        {path:'navigation-drawer',load:() => import('./navigation-drawer/navigation-drawer.js').then(m=>m.default)},
        {path:'navigation-rail',load:() => import('./navigation-rail/navigation-rail.js').then(m=>m.default)},
        {path:'tab',load:() => import('./tab/tab.js').then(m=>m.default)},
        {path:'top-app-bar',load:() => import('./top-app-bar/top-app-bar.js').then(m=>m.default)},
        {path:'form',load:() => import('./form/form.js').then(m=>m.default)},
        {path:'select-field',load:() => import('./select-field/select-field.js').then(m=>m.default)},
        {path:'textarea-field',load:() => import('./textarea-field/textarea-field.js').then(m=>m.default)},
        {path:'email-field',load:() => import('./email-field/email-field.js').then(m=>m.default)},
        {path:'password-field',load:() => import('./password-field/password-field.js').then(m=>m.default)},
        {path:'url-field',load:() => import('./url-field/url-field.js').then(m=>m.default)},
        {path:'search-field',load:() => import('./search-field/search-field.js').then(m=>m.default)},
        {path:'number-field',load:() => import('./number-field/number-field.js').then(m=>m.default)},
        {path:'tel-field',load:() => import('./tel-field/tel-field.js').then(m=>m.default)},
        {path:'date-field',load:() => import('./date-field/date-field.js').then(m=>m.default)},
        {path:'datetime-field',load:() => import('./datetime-field/datetime-field.js').then(m=>m.default)},
        {path:'month-field',load:() => import('./month-field/month-field.js').then(m=>m.default)},
        {path:'time-field',load:() => import('./time-field/time-field.js').then(m=>m.default)},
        {path:'week-field',load:() => import('./week-field/week-field.js').then(m=>m.default)},
        {path:'color-field',load:() => import('./color-field/color-field.js').then(m=>m.default)},
        {path:'file-field',load:() => import('./file-field/file-field.js').then(m=>m.default)},
        {path:'text-field',load:() => import('./text-field/text-field.js').then(m=>m.default)},
        {path:'card',load:() => import('./card/card.js').then(m=>m.default)},
        {path:'list',load:() => import('./list/list.js').then(m=>m.default)},
        {path:'side-sheet',load:() => import('./side-sheet/side-sheet.js').then(m=>m.default)},
        {path:'divider',load:() => import('./divider/divider.js').then(m=>m.default)},
        {path:'carousel',load:() => import('./carousel/carousel.js').then(m=>m.default)},
        {path:'checkbox',load:() => import('./checkbox/checkbox.js').then(m=>m.default)},
        {path:'radio-button',load:() => import('./radio-button/radio-button.js').then(m=>m.default)},
        {path:'slider',load:() => import('./slider/slider.js').then(m=>m.default)},
        {path:'switch',load:() => import('./switch/switch.js').then(m=>m.default)},
        {path:'date-picker',load:() => import('./date-picker/date-picker.js').then(m=>m.default)},
        {path:'time-picker',load:() => import('./time-picker/time-picker.js').then(m=>m.default)},
        {path:'chip',load:() => import('./chip/chip.js').then(m=>m.default)},
        {path:'menu',load:() => import('./menu/menu.js').then(m=>m.default)},
        {path:'search',load:() => import('./search/search.js').then(m=>m.default)},
        {path:'segmented-button',load:() => import('./segmented-button/segmented-button.js').then(m=>m.default)},
        {path:'data-table',load:() => import('./data-table/data-table.js').then(m=>m.default)},
        {path:'pagination',load:() => import('./pagination/pagination.js').then(m=>m.default)},
        
    ]}
])

