import { Router } from "../lib/router/router";

const devs = [
    //
    "admin",
    "auth",
    "badge",
    "blog",
    "blogs",
    "bottom-app-bar",
    "bottom-sheet",
    "button",
    "card",
    "carousel",
    "checkbox",
    "chip",
    "color-field",
    "data",
    "data-table",
    "date-field",
    "date-picker",
    "datetime-field",
    "dialog",
    "divider",
    "email-field",
    "emoji",
    "error",
    "example",
    "extended-fab",
    "fab",
    "file-field",
    "form",
    "form-field",
    "gesture",
    "icon",
    "icon-button",
    "layout",
    "list",
    "login",
    "main",
    "menu",
    "month-field",
    "navigation-bar",
    "navigation-drawer",
    "navigation-rail",
    "number-field",
    "pagination",
    "pane",
    "password-field",
    "picker",
    "popper",
    "progress-indicator",
    "radio-button",
    "range-field",
    "register",
    "ripple",
    "scroll",
    "search",
    "search-field",
    "segmented-button",
    "select-field",
    "side-sheet",
    "slider",
    "snackbar",
    "switch",
    "tab",
    "tel-field",
    "text-field",
    "textarea-field",
    "time-field",
    "time-picker",
    "tooltip",
    "top-app-bar",
    "url-field",
    "user",
    "users",
    "verify",
    "virtual-scroll",
    "week-field",
];

Router.init([
    {
        path: "",
        load: () => import("./main/main.js").then((m) => m.default),
        children: devs.map((dev) => ({
            path: dev,
            load: () => import(`./${dev}/${dev}.js`).then((m) => m.default),
        })),
    },
    {
        path: "*",
        load: () => import("./main/main.js").then((m) => m.default),
    },
]);
