[
    // "M3 Portal",
    // "Search",
    // "Home",
    // "Get started",
    // "Develop",
    // "Develop overview",
    // "Android",
    // "MDC-Android",
    // "Jetpack Compose",
    // "Flutter",
    // "Web",
    "Foundations",
    // "Foundations overview",
    // "Accessibility",
    // "Content design",
    // "Overview",
    // "Alt text",
    // "Global writing",
    // "Style guide",
    // "Customizing Material",
    // "Design tokens",
    // "Interaction",
    "Gestures",
    // "Inputs",
    "Selection",
    "States",
    "Layout",
    // "Understanding layout",
    // "Applying layout",
    // "Canonical layouts",
    // "Material A-Z",

    "Styles",
    // "Styles overview",
    "Color",
    // "Color system",
    // "Color roles",
    // "Color schemes",
    // "Choosing a scheme",
    // "Static",
    // "Dynamic",
    // "Advanced",
    // "Color resources",
    "Elevation",
    "Icons",
    "Motion",
    // "Overview",
    // "Easing and duration",
    // "Transitions",
    "Shape",
    "Typography",

    "Components",
    // "Components overview",
    // "App bars",
    "Bottom app bar",
    "Top app bar",
    "Badges",
    "Buttons",
    // "All buttons",
    // "Common buttons",
    "FAB",
    // "Extended FAB",
    "Icon buttons",
    "Segmented buttons",
    "Cards",
    "Carousel",
    "Checkbox",
    "Chips",
    "Date pickers",
    "Dialogs",
    "Divider",
    "Lists",
    "Menus",
    // "Navigation",
    "Navigation bar",
    "Navigation drawer",
    "Navigation rail",
    "Progress indicators",
    "Radio button",
    "Search",
    // "Sheets",
    "Bottom sheets",
    "Side sheets",
    "Sliders",
    "Snackbar",
    "Switch",
    "Tabs",
    "Text fields",
    "Time pickers",
    "Tooltips",

    // "Blog",
]

// Naming
// Controller
// Component
